version: "3.7"

services:
  server:
    container_name: mini-recsys-server
    build: backend/
    ports:
      - "8080:8080"
    networks:
      - deploy_network

  client:
    container_name: mini-recsys-client
    build: frontend/
    ports:
        - "8501:8501"
    networks:
      - deploy_network
    depends_on:
      - server

networks:
  deploy_network:
    driver: bridge